name: Test examples
on:
  workflow_call:
    inputs:
      api_url:
        description: "The URL of the Lamini API service"
        required: true
        type: string
    secrets:
      # Secrets cannot be passed as inputs. So we have to pass secrets separately.
      api_key:
        description: "The key of the Lamini API service"
        required: true

jobs:
  llama3:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: pip install -r ./lamini-examples/requirements.txt
      - run: |
          cd ./lamini-examples/01_llama3
          python llama3.py

  eval:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: ./lamini-examples/02_eval/scripts/eval.sh

  prompt_tuning:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: ./lamini-examples/03_prompt_tuning/scripts/prompt_tune.sh

  rag_tuning:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: pip install -r ./lamini-examples/requirements.txt
      - run: |
          cd ./lamini-examples/04_rag_tuning
          python rag.py

  data_pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: ./lamini-examples/05_data_pipeline/scripts/generate-data.sh

  ift:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: ./lamini-examples/06_ift/scripts/train.sh

  json_output:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lamini-ai/lamini-examples
          path: lamini-examples
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup remote service config
        run: |
          echo LAMINI_API_URL=${{ inputs.api_url }} >>  ${GITHUB_ENV}
          echo LAMINI_API_KEY=${{ secrets.api_key }} >>  ${GITHUB_ENV}
      - run: ./lamini-examples/10_json_output/scripts/run_llm_json.sh
